# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-27 03:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='days_past_due',
            field=models.SmallIntegerField(null=True),
        ),
    ]
