# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0003_auto_20160526_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='number',
            field=models.SmallIntegerField(editable=False),
        ),
    ]
