# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0004_auto_20160528_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='code',
            field=models.SlugField(default='x'),
            preserve_default=False,
        ),
    ]
