# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0006_auto_20160528_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='days_past_due',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
    ]
