# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0007_auto_20160528_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='days_past_due',
            field=models.SmallIntegerField(blank=True, editable=False, null=True),
        ),
    ]
