# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0008_auto_20160528_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='item_max',
            field=models.SmallIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='due_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
