# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0009_auto_20160530_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='code',
            field=models.SlugField(default='CODE', editable=False),
            preserve_default=False,
        ),
    ]
