# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slib', '0011_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.SmallIntegerField(choices=[('Available', 0), ('Checked Out', 1), (None, 2), (None, 3)], default=0, editable=False),
        ),
    ]
